# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push: null
  pull_request: null
  merge_group: null
  workflow_dispatch:
    inputs:
      full_scan:
        type: boolean
        default: false
        required: false
        description: "Lint all codebase"

# Don't grant any access by default
permissions: {}

jobs:
  run-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
    - name: "Get the common linters configuration"
      uses: actions/checkout@v4
      with:
        ref: main
        path: super-linter-common-configs
        repository: netcracker/.github
        sparse-checkout: |
          .github/linters
          .github/super-linter.env
        
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
        path: ${GITHUB_WORKSPACE}/code-to-lint
    - name: "Apply common linters configuration"
      shell: bash
      run: |
        pwd
        ls -la .
        ls -la ${GITHUB_WORKSPACE}/super-linter-common-configs
        ls -la ${GITHUB_WORKSPACE}/super-linter-common-configs/.github
        if [ -d ${GITHUB_WORKSPACE}/code-to-lint/.github/linters ]; then
          echo "❕ Found local linter configuration files. Applying."
          cp -fR ${GITHUB_WORKSPACE}/code-to-lint/.github/linters ${GITHUB_WORKSPACE}/super-linter-common-configs/.github
        fi

    - name: "Load super-linter environment file"
      shell: bash
      run: |
        # shellcheck disable=2086
        if [ -f "${GITHUB_WORKSPACE}/super-linter-common-configs/.github/super-linter.env" ]; then
          echo "❕ Applying common linter environment:"
          grep "\S" ${GITHUB_WORKSPACE}/super-linter-common-configs/.github/super-linter.env | grep -v "^#"
          grep "\S" ${GITHUB_WORKSPACE}/super-linter-common-configs/.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi
        if [ -f "${GITHUB_WORKSPACE}/code-to-lint/.github/super-linter.env" ]; then
          echo "❕ Applying local linter environment:"
          grep "\S" ${GITHUB_WORKSPACE}/code-to-lint/.github/super-linter.env | grep -v "^#"
          grep "\S" ${GITHUB_WORKSPACE}/code-to-lint/.github/super-linter.env | grep -v "^#" >> $GITHUB_ENV
        fi

    - name: Lint Code Base
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan || false }}
        DEFAULT_BRANCH: "main"
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_WORKSPACE: ${GITHUB_WORKSPACE}/code-to-lint
        LINTER_RULES_PATH: ${GITHUB_WORKSPACE}/super-linter-common-configs/.github/linters
